version: '2.1'
services:
    mongodata:
        image: mongo:3.3.10
        volumes:
            - /Users/tuanpa/Work/eos/data/mongodata:/data/db
        command: bash -c "rm /data/db/mongod.lock"
    mongo:
        image: mongo:3.3.10
        volumes:
            - ./:/tempo:rw
        volumes_from:
            - mongodata
        ports:
            - "27017:27017"
        command: --smallfiles --rest
